title: "Tatiana Molina"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme         
description: "Operations Director / VP â€” GTM Enablement, Revenue and Customer Operations | SaaS growth | PE-backed transformation"
show_downloads: false
github:
  is_project_page: false
