title: "Tatiana Molina"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme         
description: "Operations Director / VP â€” Revenue Operations, Data & GTM Enablement | SaaS | PE-backed Companies"
show_downloads: false
github:
  is_project_page: false
